### ISSUE TITLE
如何转ncnn模型

### ISSUE THREAD

**Issue by zgsxwsdxg** [zhouweigogogo/yolov10-ncnn#1]
你好，大神，问下yolov10从pytorch模型转ncnn模型的具体步骤，谢谢

**Comment by zhouweigogogo** [comment]
你好，yolov10的转化步骤我是先导出torchscript，然后使用PNNX转化。在此之前，我尝试过使用ONNX转NCNN，但是存在一些问题。导出torchscript可以使用三木君的https://github.com/triple-Mu/yolov10。

**Comment by zgsxwsdxg** [comment]
> 你好，yolov10的转化步骤我是先导出torchscript，然后使用PNNX转化。在此之前，我尝试过使用ONNX转NCNN，但是存在一些问题。导出torchscript可以使用三木君的[https://github.com/triple-Mu/yolov10。](https://github.com/triple-Mu/yolov10%E3%80%82)

谢谢您的回复，我想问下，导出torchscript后，如何使用pnnx转ncnn？这个是用哪个命令？是否可以指导下？

我目前是，通过官网yolov10仓库直接导出ncnn，具体导出代码是：
from ultralytics import YOLO
model = YOLO("./pretrain_weights/yolov10n.pt")
model.export(format="ncnn",half=True)

然后把导出的模型用您的代码测试，报错如下：
(base) dxg@hpw:~/yolov10-ncnn/build$ ./yolov10_ncnn ../img/bus.jpg 
layer torch.topk not exists or registered
段错误 (核心已转储)

**Comment by quocnhat** [comment]
Hi, Do you have any updates? I got the same error.
Please add some guidance to README to help converting yolov10 to ncnn format.
Thank you

**Comment by zhouweigogogo** [comment]
晚些我会更新ncnn的转化细节

**Comment by HZYO-0** [comment]
> 晚些我会更新ncnn的转化细节

期待大佬的转化细节，快被逼疯了

**Comment by quocnhat** [comment]
I've followed step by step:
torch -> torchscript -> pnnx->net.ncnn.param -> remove post process and then add new post process ( permute + sigmoid)
Now, by using visualization tool, my model structure is the same as @zhouweigogogo 's one but the output is still crazy.
Please help!

**Comment by quocnhat** [comment]
@all To whom may need: The steps I proposed before can work now. We have to load the pretrained weight after init the model.

**Comment by quocnhat** [comment]
To whom may need: The followed steps work:
torch -> torchscript -> pnnx->net.ncnn.param -> remove post process and then add new post process ( permute + sigmoid). Please use visualization tools to see the postprocess layer from @zhouweigogogo

**Comment by zhouweigogogo** [comment]
sorry，现在已更新，详情见model_convert_CN.md
